### ISSUE TITLE
能不能关注一下隐私

### ISSUE THREAD

**Issue by f846834361** [DebugingOnProd/douban-api#6]
启动了一下项目,日志里面有你真实姓名

**Comment by DebugingOnProd** [comment]
您好，收到你这个消息后我立马查看了一下我的项目代码，我注意到测试数据里确实有一些人的名字，不过那些都是书本作家的名字，您指的姓名是只配置文件中的 文件夹名称 或者 包名 中疑似姓名缩写的部分吗

**Comment by f846834361** [comment]
对对对,我看错了,你删了吧
